version: '3.8'

services:
  web:
    image: aspnet
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    volumes:
      - ./ImagesBindMount:/app/ImagesBindMount
      - ImagesVolume:/app/ImagesVolume

volumes:
  ImagesVolume:
